# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/crawler/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      dependency-type: "all"
    
  - package-ecosystem: "gomod"
    directory: "/backend/" 
    schedule:
      interval: "weekly"
    allow:
      dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    allow:
      dependency-type: "all"
    
