# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Crawler CI (Go)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go (1.23.6)
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'
        check-latest: true
        cache-dependency-path: ./crawler/go.sum
    
    - name: Build Crawler
      working-directory: ./crawler
      run: go build -v

    - name: Test Crawler
      working-directory: ./crawler
      run: go test -v
