# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  go_fmt:
    name: Format Go Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      
      - name: Run gofmt on crawler
        working-directory: ./crawler
        run: go fmt .

      - name: Run gofmt on backend
        working-directory: ./backend
        run: go fmt .

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore(crawler, backend): fix formatting'


  build_crawler:      
    name: Crawler Build And Test (Go)
    needs: go_fmt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4

    - name: Set up Go (1.23.6)
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'
        check-latest: true
        cache-dependency-path: ./crawler/go.sum
    
    - name: Build Crawler
      working-directory: ./crawler
      run: go build -v

    - name: Test Crawler
      working-directory: ./crawler
      run: go test -v
  
  build_backend:
    name: Backend Build And Test (Go)
    needs: go_fmt
    runs-on: ubuntu-latest
    steps:
    - name: Chdckout PR branch
      uses: actions/checkout@v4

    - name: Set up Go (1.23.6)
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.6'
        check-latest: true
        cache-dependency-path: ./backend/go.sum
    
    - name: Build Backend
      working-directory: ./backend
      run: go build -v

    - name: Test Backend
      working-directory: ./backend
      run: go test -v
