# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go (crawler)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go (1.23.6)
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'
    
    - name: Build
      run: go build -v ./crawler/...

    - name: Test
      run: go test -v ./crawler/..
