# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Crawler CI (Go)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    name: Format Go Code (Crawler)
    permissions:
      contents: write
      
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        # This is important to fetch the changes to the previous commit
        fetch-depth: 0
    
    - name: Run gofmt
      working-directory: ./crawler
      run: go fmt .

    - name: Commit gofmt changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        fetch: true
        pathspec_error_handling: ignore
        message: 'style(crawler): formatting'


  build:      
    name: Crawler Build And Test (Go)
    needs: format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
    
    - name: Build Crawler
      working-directory: ./crawler
      run: go build -v

    - name: Test Crawler
      working-directory: ./crawler
      run: go test -v